name = "FoldsThreadsExtras"
uuid = "0b9379b8-075f-4c58-8222-3c77c9364ad9"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SplittablesBase = "171d559e-b47b-412a-8079-5efa626c420e"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
